{-
   AWS Lambda Runtime API

   AWS Lambda Runtime API is an HTTP API for implementing custom runtimes

   OpenAPI Version: 3.0.0
   AWS Lambda Runtime API API version: 1.0.3
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : AWSLambdaRuntime.API
-}

module AWSLambdaRuntime.API
  ( module AWSLambdaRuntime.API.ApiDefault
  ) where

import AWSLambdaRuntime.API.ApiDefault