{-
   AWS Lambda Runtime API

   AWS Lambda Runtime API is an HTTP API for implementing custom runtimes

   OpenAPI Version: 3.0.0
   AWS Lambda Runtime API API version: 1.0.3
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : AWSLambdaRuntime.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module AWSLambdaRuntime.Logging
  ( module AWSLambdaRuntime.LoggingKatip
  ) where

import AWSLambdaRuntime.LoggingKatip

#else

module AWSLambdaRuntime.Logging
  ( module AWSLambdaRuntime.LoggingMonadLogger
  ) where

import AWSLambdaRuntime.LoggingMonadLogger

#endif
