name: Node Publish

on:
  push:
    branches:
    - master

jobs:
  publish:
    steps:
    - name: npm publish
      uses: actions/npm@master
      args: publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    
