name: Node Publish

on: [push]
push:
  branches:
  - master

jobs:
  publish:
    steps:
    - name: npm publish
      uses: actions/npm@master
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    
